import { ArrowDown, Bug, RefreshCw, Send, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router";
import { PageContainer } from "@/components/page-container";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { readOperationLanguage } from "@/lib/operation-definition/language";
import { listAvailableOperations } from "@/lib/operation-definition/operation-loader";
import { buildOperationDebugBundle } from "@/lib/prompt-composition-engine/debug-preview.server";
import { cn } from "@/lib/utils";
import { CopyablePromptBlock } from "./components/copyable-prompt-block";
import type { Route } from "./+types/route";

type LoaderData = {
  activeStepId: string;
  userMessage: string;
  operations: string[];
  previousResponse: string;
  preview: ReturnType<typeof buildOperationDebugBundle> | null;
  reportDetails: string;
  reportSummary: string;
  selectedOperation: string | null;
  taskInstruction: string;
};

function getLanguage(): string {
  return readOperationLanguage();
}

function PrettyCode({ className, value }: { className?: string; value: string }) {
  return (
    <pre
      className={cn(
        "max-h-136 overflow-auto rounded-lg border border-slate-700 bg-slate-950 p-4 font-mono text-[12px] leading-5 whitespace-pre-wrap text-slate-100",
        className,
      )}
    >
      {value}
    </pre>
  );
}

export const loader = async ({ request }: Route.LoaderArgs) => {
  const url = new URL(request.url);
  const language = getLanguage();
  const operations = listAvailableOperations(language).sort((left, right) => left.localeCompare(right));
  const requestedOperation = url.searchParams.get("operation")?.trim() || null;
  const selectedOperation =
    requestedOperation && operations.includes(requestedOperation)
      ? requestedOperation
      : (operations[0] ?? null);

  const taskInstruction =
    url.searchParams.get("task")?.trim() || "Implement the selected step exactly as Noctis delegated it.";
  const userMessage =
    url.searchParams.get("userMessage")?.trim() || "This is a synthetic User message for operation activation.";
  const previousResponse =
    url.searchParams.get("previousResponse")?.trim() || "Synthetic previous step output";
  const reportSummary =
    url.searchParams.get("reportSummary")?.trim() || "Synthetic report from worker";
  const reportDetails =
    url.searchParams.get("reportDetails")?.trim() ||
    "No additional details. This is synthetic content generated by operation-debug.";

  const preview =
    selectedOperation
      ? buildOperationDebugBundle({
          userMessage,
          operationName: selectedOperation,
          taskInstruction,
          previousResponse,
          reportSummary,
          reportDetails,
        })
      : null;

  const activeStepParam = url.searchParams.get("step")?.trim() || null;
  const activeStepId =
    activeStepParam && preview?.flowSteps.some((step) => step.id === activeStepParam)
      ? activeStepParam
      : (preview?.flowSteps[0]?.id ?? "");

  return {
    activeStepId,
    userMessage,
    operations,
    selectedOperation,
    taskInstruction,
    previousResponse,
    reportSummary,
    reportDetails,
    preview,
  } satisfies LoaderData;
};

const OperationDebugPage = ({ loaderData }: Route.ComponentProps) => {
  const navigate = useNavigate();
  const [selectedOperation, setSelectedOperation] = useState(loaderData.selectedOperation ?? "");
  const [activeStepId, setActiveStepId] = useState(loaderData.activeStepId);
  const [userMessage, setUserMessage] = useState(loaderData.userMessage);
  const [taskInstruction, setTaskInstruction] = useState(loaderData.taskInstruction);
  const [previousResponse, setPreviousResponse] = useState(loaderData.previousResponse);
  const [reportSummary, setReportSummary] = useState(loaderData.reportSummary);
  const [reportDetails, setReportDetails] = useState(loaderData.reportDetails);

  useEffect(() => {
    setSelectedOperation(loaderData.selectedOperation ?? "");
    setActiveStepId(loaderData.activeStepId);
    setUserMessage(loaderData.userMessage);
    setTaskInstruction(loaderData.taskInstruction);
    setPreviousResponse(loaderData.previousResponse);
    setReportSummary(loaderData.reportSummary);
    setReportDetails(loaderData.reportDetails);
  }, [loaderData]);

  const navigateWithPreviewParams = ({
    userInput,
    operation,
    previous,
    reportBody,
    reportMeta,
    stepId,
    task,
  }: {
    userInput: string;
    operation: string;
    previous: string;
    reportBody: string;
    reportMeta: string;
    stepId: string;
    task: string;
  }) => {
    const params = new URLSearchParams();
    if (operation) {
      params.set("operation", operation);
    }
    if (stepId) {
      params.set("step", stepId);
    }
    if (userInput.trim()) {
      params.set("userMessage", userInput.trim());
    }
    if (task.trim()) {
      params.set("task", task.trim());
    }
    if (previous.trim()) {
      params.set("previousResponse", previous.trim());
    }
    if (reportBody.trim()) {
      params.set("reportSummary", reportBody.trim());
    }
    if (reportMeta.trim()) {
      params.set("reportDetails", reportMeta.trim());
    }
    void navigate(`/operation-debug?${params.toString()}`);
  };

  const handleGenerate = () => {
    navigateWithPreviewParams({
      userInput: userMessage,
      operation: selectedOperation,
      stepId: activeStepId,
      task: taskInstruction,
      previous: previousResponse,
      reportBody: reportSummary,
      reportMeta: reportDetails,
    });
  };

  const handleReset = () => {
    const operation = loaderData.operations[0] ?? "";
    setSelectedOperation(operation);
    setActiveStepId("");
    setUserMessage("This is a synthetic User message for operation activation.");
    setTaskInstruction("Implement the selected step exactly as Noctis delegated it.");
    setPreviousResponse("Synthetic previous step output");
    setReportSummary("Synthetic report from worker");
    setReportDetails("No additional details. This is synthetic content generated by operation-debug.");
    void navigate("/operation-debug");
  };

  const bundle = loaderData.preview;
  const selectedStep = useMemo(
    () => bundle?.flowSteps.find((step) => step.id === activeStepId) ?? bundle?.flowSteps[0] ?? null,
    [bundle, activeStepId],
  );

  const selectedStepNumber = useMemo(() => {
    if (!bundle?.flowSteps.length || !selectedStep) {
      return null;
    }

    const index = bundle.flowSteps.findIndex((step) => step.id === selectedStep.id);
    return index >= 0 ? index + 1 : null;
  }, [bundle, selectedStep]);

  const facetStats = useMemo(() => {
    if (!selectedStep?.resolvedFacets) {
      return [] as Array<{ label: string; value: string }>;
    }

    return [
      { label: "Job", value: selectedStep.resolvedFacets.job ? "loaded" : "missing" },
      {
        label: "Instruction",
        value: selectedStep.resolvedFacets.instruction ? "loaded" : "missing",
      },
      {
        label: "Knowledge",
        value:
          selectedStep.resolvedFacets.knowledge.length > 0
            ? `${selectedStep.resolvedFacets.knowledge.length} loaded`
            : "missing",
      },
      {
        label: "Policy",
        value:
          selectedStep.resolvedFacets.policies.length > 0
            ? `${selectedStep.resolvedFacets.policies.length} loaded`
            : "missing",
      },
      {
        label: "Output Contract",
        value:
          selectedStep.resolvedFacets.outputContracts.length > 0
            ? `${selectedStep.resolvedFacets.outputContracts.length} loaded`
            : "missing",
      },
    ];
  }, [selectedStep]);

  const finalPrompt = useMemo(() => {
    if (!selectedStep) {
      return "No preview available.";
    }

    return selectedStep.effectivePrompt ?? selectedStep.injectedPrompt;
  }, [selectedStep]);

  const assemblyBlocks = useMemo(() => {
    if (!selectedStep) {
      return [] as Array<{
        id: string;
        title: string;
        placement: string;
        rendering: "Displayed" | "Embedded";
        content: string;
      }>;
    }

    const blocks: Array<{
      id: string;
      title: string;
      placement: string;
      rendering: "Displayed" | "Embedded";
      content: string;
    }> = [
      {
        id: "internal",
        title: "Internal Context",
        placement: "Block 1 in final prompt",
        rendering: "Displayed",
        content: selectedStep.internalContext,
      },
    ];

    if (selectedStep.suppressedContext?.trim()) {
      blocks.push({
        id: "suppressed",
        title: "Suppressed Metadata",
        placement: "Debug-only metadata panel",
        rendering: "Displayed",
        content: selectedStep.suppressedContext,
      });
    }

    if (selectedStep.kind === "self") {
      blocks.push(
        {
          id: "injected",
          title: "Operation Activation",
          placement: "Block 2 in final prompt",
          rendering: "Displayed",
          content: selectedStep.injectedPrompt,
        },
        {
          id: "source",
          title: "User Routed Message",
          placement: "Block 3 in final prompt",
          rendering: "Displayed",
          content: selectedStep.sourceInput,
        },
      );
    } else if (selectedStep.kind === "dispatch") {
      blocks.push(
        {
          id: "source",
          title: "Source Task Input",
          placement: "Embedded inside Injected Prompt > Task section",
          rendering: "Embedded",
          content: selectedStep.sourceInput,
        },
        {
          id: "injected",
          title: "Injected Worker Prompt",
          placement: "Block 2 in final prompt",
          rendering: "Displayed",
          content: selectedStep.injectedPrompt,
        },
      );
    } else {
      blocks.push(
        {
          id: "source",
          title: "Worker Report Envelope",
          placement: "Block 2 in final prompt",
          rendering: "Displayed",
          content: selectedStep.sourceInput,
        },
        {
          id: "injected",
          title: "Noctis Guidance",
          placement: "Appended after report envelope when generated",
          rendering: "Displayed",
          content: selectedStep.injectedPrompt,
        },
      );
    }

    return blocks;
  }, [selectedStep]);

  const diagnosticsBlocks = useMemo(() => {
    if (!selectedStep) {
      return [] as Array<{ id: string; title: string; content: string }>;
    }

    return [
      {
        id: "rule",
        title: "Rule / Transition",
        content: selectedStep.ruleEvaluation ?? selectedStep.ruleTransition ?? "No rule diagnostics for this step.",
      },
      {
        id: "context",
        title: "Step Context",
        content: selectedStep.operationContextSummary ?? "No context available.",
      },
      {
        id: "facets",
        title: "Resolved Facets",
        content:
          selectedStep.resolvedFacets
            ? [
                `job: ${selectedStep.resolvedFacets.job ? "loaded" : "missing"}`,
                `instruction: ${selectedStep.resolvedFacets.instruction ? "loaded" : "missing"}`,
                `knowledge: ${selectedStep.resolvedFacets.knowledge.length}`,
                `policy: ${selectedStep.resolvedFacets.policies.length}`,
                `output_contracts: ${selectedStep.resolvedFacets.outputContracts.length}`,
              ].join("\n")
            : "No facet data available.",
      },
    ];
  }, [selectedStep]);

  const flowToneClass = (kind: string, selected: boolean) => {
    if (selected) {
      return "border-blue-400 bg-blue-950/80 shadow-lg ring-2 ring-blue-400/60";
    }

    if (kind === "self") {
      return "border-sky-950 bg-sky-950/20 opacity-60 hover:border-sky-800 hover:bg-sky-950/35 hover:opacity-80";
    }
    if (kind === "dispatch") {
      return "border-amber-950 bg-amber-950/20 opacity-60 hover:border-amber-800 hover:bg-amber-950/35 hover:opacity-80";
    }
    return "border-violet-950 bg-violet-950/20 opacity-60 hover:border-violet-800 hover:bg-violet-950/35 hover:opacity-80";
  };

  return (
    <PageContainer className="max-w-none gap-4 overflow-hidden bg-slate-950 px-4 text-slate-100" size="wide">
      <div className="border-border/50 border-b pb-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Badge className="gap-1.5 text-white" variant="default">
                <Bug className="h-3.5 w-3.5" />
                Operation Debug
              </Badge>
              {selectedStepNumber ? <Badge variant="outline">Step {selectedStepNumber}</Badge> : null}
            </div>
            <p className="max-w-4xl text-slate-300 text-sm">
              Flow blocks are generated from every step in the selected operation YAML.
              Click a block to inspect exact injected prompt, internal context, and transition details.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <Button onClick={handleReset} size="sm" variant="outline">
              <RefreshCw className="h-4 w-4" />
              Reset
            </Button>
            <Button className="" onClick={handleGenerate} size="sm">
              <Wrench className="h-4 w-4" />
              Regenerate
            </Button>
          </div>
        </div>
      </div>

      <div className="grid min-h-0 flex-1 gap-4 overflow-hidden xl:grid-cols-[30rem_minmax(0,1fr)]">
        <Card className="flex h-full min-h-0 flex-col overflow-hidden border-slate-800 bg-slate-900 text-slate-100">
          <CardHeader className="border-b border-slate-800 bg-slate-900">
            <CardTitle className="text-lg">Flow</CardTitle>
            <CardDescription className="text-slate-400">
              End-to-end handoff map. All steps in the selected operation are shown.
            </CardDescription>
          </CardHeader>
          <CardContent className="min-h-0 flex flex-1 flex-col gap-4 overflow-hidden">
            <div className="space-y-2">
              <label className="font-medium text-sm" htmlFor="operation-select">
                Operation
              </label>
              <Select
                onValueChange={(value) => {
                  setSelectedOperation(value);
                  navigateWithPreviewParams({
                    userInput: userMessage,
                    operation: value,
                    stepId: "",
                    task: taskInstruction,
                    previous: previousResponse,
                    reportBody: reportSummary,
                    reportMeta: reportDetails,
                  });
                }}
                value={selectedOperation}
              >
                <SelectTrigger className="border-slate-700 bg-slate-950 text-slate-100 data-placeholder:text-slate-500" id="operation-select">
                  <SelectValue placeholder="Select an operation" />
                </SelectTrigger>
                <SelectContent className="border-slate-700 bg-slate-900 text-slate-100">
                  {loaderData.operations.map((operation) => (
                    <SelectItem className="text-slate-100 focus:bg-slate-800 focus:text-slate-100" key={operation} value={operation}>
                      {operation}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Tabs className="min-h-0 flex flex-1 flex-col" defaultValue="flow">
              <TabsList className="w-full justify-start border-slate-800" variant="line">
                <TabsTrigger className="" value="flow" variant="line">
                  Flow
                </TabsTrigger>
                <TabsTrigger className="" value="inputs" variant="line">
                  Inputs
                </TabsTrigger>
              </TabsList>

              <TabsContent className="min-h-0 flex-1 overflow-auto pr-1" value="flow">
                <div className="space-y-2">
                  {(bundle?.flowSteps ?? []).map((step, index, arr) => {
                    const selected = step.id === selectedStep?.id;
                    const stepNumber = index + 1;
                    return (
                      <div key={step.id}>
                        <button
                          className={cn(
                            "w-full cursor-pointer rounded-lg border p-3 text-left transition-all",
                            flowToneClass(step.kind, selected),
                          )}
                          onClick={() => {
                            setActiveStepId(step.id);
                            navigateWithPreviewParams({
                              userInput: userMessage,
                              operation: selectedOperation,
                              stepId: step.id,
                              task: taskInstruction,
                              previous: previousResponse,
                              reportBody: reportSummary,
                              reportMeta: reportDetails,
                            });
                          }}
                          type="button"
                        >
                          <div className="flex items-center justify-between gap-2">
                            <div className="flex items-center gap-3">
                              <div
                                className={cn(
                                  "flex h-7 w-7 items-center justify-center rounded-full border text-xs font-bold",
                                  selected
                                    ? "border-blue-300 bg-blue-500 text-white"
                                    : "border-slate-700 bg-slate-950/90 text-slate-400",
                                )}
                              >
                                {stepNumber}
                              </div>
                              <div className={cn("font-semibold text-sm", selected ? "text-slate-50" : "text-slate-300")}>
                                {step.title}
                              </div>
                            </div>
                            <Badge
                              className={cn(
                                "border-slate-600",
                                selected ? "text-blue-100" : "text-slate-400",
                              )}
                              variant="outline"
                            >
                              {step.hookId}
                            </Badge>
                          </div>
                          <div className={cn("mt-1 flex items-center gap-2 text-xs", selected ? "text-slate-200" : "text-slate-500")}>
                            <Send className="h-3 w-3" />
                            {step.from} -&gt; {step.to}
                          </div>
                          <div className={cn("mt-2 text-xs", selected ? "text-slate-300" : "text-slate-500")}>
                            {step.summary}
                          </div>
                        </button>

                        {index < arr.length - 1 ? (
                          <div className="flex justify-center py-2">
                            <ArrowDown className="h-4 w-4 text-slate-600" />
                          </div>
                        ) : null}
                      </div>
                    );
                  })}
                </div>
              </TabsContent>

              <TabsContent className="min-h-0 flex-1 space-y-4 overflow-auto pr-1" value="inputs">
                <div className="space-y-2 rounded-lg border border-blue-800 bg-blue-950/40 p-3 text-slate-100">
                  <label className="font-medium text-sm" htmlFor="user-message">
                    User Message (Hook 1)
                  </label>
                  <Textarea
                    id="user-message"
                    onChange={(event) => setUserMessage(event.target.value)}
                    rows={4}
                    value={userMessage}
                  />
                </div>

                <div className="space-y-2 rounded-lg border border-amber-800 bg-amber-950/40 p-3 text-slate-100">
                  <label className="font-medium text-sm" htmlFor="task-instruction">
                    Synthetic Task (Dispatch)
                  </label>
                  <Textarea
                    id="task-instruction"
                    onChange={(event) => setTaskInstruction(event.target.value)}
                    rows={4}
                    value={taskInstruction}
                  />
                </div>

                <div className="space-y-2 rounded-lg border border-sky-800 bg-sky-950/40 p-3 text-slate-100">
                  <label className="font-medium text-sm" htmlFor="previous-response">
                    Synthetic Previous Response
                  </label>
                  <Textarea
                    id="previous-response"
                    onChange={(event) => setPreviousResponse(event.target.value)}
                    rows={3}
                    value={previousResponse}
                  />
                </div>

                <div className="space-y-2 rounded-lg border border-violet-800 bg-violet-950/40 p-3 text-slate-100">
                  <label className="font-medium text-sm" htmlFor="report-summary">
                    Synthetic Report Summary (Report)
                  </label>
                  <Textarea
                    id="report-summary"
                    onChange={(event) => setReportSummary(event.target.value)}
                    rows={4}
                    value={reportSummary}
                  />
                </div>

                <div className="space-y-2 rounded-lg border border-violet-800 bg-violet-950/40 p-3 text-slate-100">
                  <label className="font-medium text-sm" htmlFor="report-details">
                    Synthetic Report Details (Report)
                  </label>
                  <Textarea
                    id="report-details"
                    onChange={(event) => setReportDetails(event.target.value)}
                    rows={4}
                    value={reportDetails}
                  />
                </div>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>

        <div className="min-h-0 space-y-4 overflow-auto pr-1">
          <Card className="border-slate-800 bg-slate-900 text-slate-100">
            <CardHeader className="pb-2">
              <CardTitle className="text-base">Selected Step</CardTitle>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-3">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-600 font-semibold text-sm text-white">
                      {selectedStepNumber ?? "-"}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <div className="font-semibold text-base text-slate-50">{selectedStep?.title ?? "-"}</div>
                        <Badge className="border-slate-600 text-blue-100" variant="outline">
                          {selectedStep?.hookId ?? "-"}
                        </Badge>
                        <Badge className="w-fit gap-1.5 border-slate-600 text-slate-200" variant="outline">
                          {selectedStep?.targetAgent ?? "-"}
                        </Badge>
                      </div>
                      <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs">
                        <div className="font-mono text-slate-500">{selectedStep?.id ?? "-"}</div>
                        <div className="flex items-center gap-1.5 text-slate-300">
                          <Send className="h-3.5 w-3.5 shrink-0" />
                          <span>{selectedStep ? `${selectedStep.from} -> ${selectedStep.to}` : "-"}</span>
                        </div>
                        <div className="min-w-0 flex-1 truncate text-slate-400">
                          {selectedStep?.summary ?? "-"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-slate-800 bg-slate-900 text-slate-100">
            <CardHeader>
              <CardTitle className="text-lg">Prompt Details</CardTitle>
              <CardDescription className="text-slate-400">
                Final prompt first, then assembly order, then supporting diagnostics.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Tabs defaultValue="final">
                <TabsList className="w-full justify-start border-slate-800" variant="line">
                  <TabsTrigger className="" value="final" variant="line">
                    Final Prompt
                  </TabsTrigger>
                  <TabsTrigger className="" value="assembly" variant="line">
                    Assembly
                  </TabsTrigger>
                  <TabsTrigger className="" value="diagnostics" variant="line">
                    Diagnostics
                  </TabsTrigger>
                </TabsList>

                <TabsContent className="space-y-4" value="final">
                  <CopyablePromptBlock
                    className="border-blue-900 bg-blue-950/30"
                    headerContent={
                      <div>
                        <div className="text-blue-200 text-xs uppercase tracking-wide">Rendered Order</div>
                        <div className="mt-2 flex flex-wrap gap-2 text-xs">
                          {assemblyBlocks.map((block, index) => (
                            <Badge className="border-slate-600 text-slate-200" key={block.id} variant="outline">
                              {index + 1}. {block.title}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    }
                    highlightTexts={selectedStep?.sourceInput ? [selectedStep.sourceInput] : []}
                    preClassName="max-h-[34rem]"
                    title="Final Prompt"
                    value={finalPrompt}
                  />
                </TabsContent>

                <TabsContent className="space-y-3" value="assembly">
                  {assemblyBlocks.map((block, index) => (
                    <CopyablePromptBlock
                      key={block.id}
                      preClassName="max-h-52"
                      title={block.title}
                      description={block.placement}
                      value={block.content}
                      headerContent={
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div className="flex items-center gap-2">
                            <div className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-800 text-xs font-semibold text-slate-100">
                              {index + 1}
                            </div>
                            <div className="font-medium text-slate-100 text-sm">{block.title}</div>
                          </div>
                          <Badge
                            className={cn(
                              "border-slate-600",
                              block.rendering === "Displayed" ? "text-blue-200" : "text-amber-200",
                            )}
                            variant="outline"
                          >
                            {block.rendering}
                          </Badge>
                        </div>
                      }
                    />
                  ))}
                </TabsContent>

                <TabsContent className="space-y-4" value="diagnostics">
                  <div className="grid gap-3 md:grid-cols-5">
                    {facetStats.map((stat) => (
                      <div className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-slate-100" key={stat.label}>
                        <div className="text-slate-400 text-xs uppercase tracking-wide">{stat.label}</div>
                        <div className="mt-1 font-medium text-sm">{stat.value}</div>
                      </div>
                    ))}
                  </div>

                  {diagnosticsBlocks.map((block) => (
                    <div className="space-y-2" key={block.id}>
                      <div className="font-medium text-sm text-slate-200">{block.title}</div>
                      <PrettyCode className="max-h-64" value={block.content} />
                    </div>
                  ))}
                </TabsContent>
                
                <TabsContent value="unused" />
              </Tabs>
            </CardContent>
          </Card>
        </div>
      </div>
    </PageContainer>
  );
};

export default OperationDebugPage;
