import { readAppConfig } from "@/lib/app-config.server";
import { getProjectRoot } from "@/lib/get-project-root.server";
import { buildInjectedPromptContext } from "@/lib/prompt-context.server";
import { buildRoutedMessageEnvelope, buildTeamMessageEnvelope } from "@/lib/team-message-format";
import type { AgentId, MovementHistoryEntry, ReportStatus, WorkerAgentId } from "@/lib/types/mission";
import { processReport } from "./engine";
import { resolveMovementFacets } from "./facet-loader";
import {
  buildActivationInstruction,
  buildAugmentedInstruction,
  buildOperationContextSummary,
} from "./instruction-builder";
import { loadOperationByName } from "./operation-loader";
import { createOperationState } from "./state";
import type { MovementDefinition, OperationDefinition, ResolvedFacets } from "./types";

export type PreviewNodeId = "hook1" | "hook2" | "hook3";
export type FlowStepKind = "self" | "dispatch" | "report";

export interface FlowStepPreview {
  id: string;
  movementName: string;
  movementIndex: number;
  kind: FlowStepKind;
  hookId: PreviewNodeId;
  title: string;
  from: string;
  to: string;
  summary: string;
  sourceInput: string;
  internalContext: string;
  injectedPrompt: string;
  effectivePrompt?: string;
  ruleEvaluation?: string;
  ruleTransition?: string;
  operationContextSummary: string;
  normalizedMovement: MovementDefinition;
  resolvedFacets?: ResolvedFacets;
  targetAgent?: AgentId;
}

export interface OperationDebugBundle {
  flowSteps: FlowStepPreview[];
  operation: OperationDefinition;
  reportDir: string;
}

function getLanguage(): string {
  try {
    const config = readAppConfig(getProjectRoot());
    return config.language || "en";
  } catch {
    return "en";
  }
}

function toWorkerAgent(agent: string): WorkerAgentId {
  return agent === "ignis" || agent === "gladiolus" || agent === "prompto"
    ? agent
    : "gladiolus";
}

function buildSyntheticHistory(operation: OperationDefinition, currentMovementName: string) {
  const now = new Date().toISOString();
  const currentIndex = operation.movements.findIndex((movement) => movement.name === currentMovementName);
  if (currentIndex <= 0) {
    return [] as MovementHistoryEntry[];
  }

  return operation.movements.slice(0, currentIndex).map((movement, index) => ({
    movement: movement.name,
    agent: movement.agent,
    status: "completed" as const,
    dispatchedAt: now,
    completedAt: now,
    ruleMatched: 0,
    ruleCondition: movement.rules[0]?.condition ?? "completed",
    nextMovement: operation.movements[index + 1]?.name ?? "COMPLETE",
    summary: `Synthetic summary for ${movement.name}`,
  }));
}

function buildStateForMovement(
  operation: OperationDefinition,
  movement: MovementDefinition,
  previousResponse: string,
) {
  const state = createOperationState(operation.name, operation.initial_movement, operation.max_movements);
  const movementIndex = operation.movements.findIndex((item) => item.name === movement.name);

  state.currentMovement = movement.name;
  state.iteration = Math.max(movementIndex, 0);
  state.movementHistory = buildSyntheticHistory(operation, movement.name);
  state.previousResponse = previousResponse;
  state.status = "running";

  return state;
}

export function buildOperationDebugBundle(input: {
  crystalMessage?: string;
  operationName: string;
  previousResponse?: string;
  reportDetails?: string;
  reportStatus?: ReportStatus;
  reportSummary?: string;
  taskInstruction?: string;
}): OperationDebugBundle {
  const root = getProjectRoot();
  const language = getLanguage();
  const operation = loadOperationByName(input.operationName, language);

  const reportStatus = input.reportStatus ?? "completed";
  const crystalMessageBase =
    input.crystalMessage?.trim() || "This is a synthetic Crystal message for operation activation.";
  const reportSummaryBase = input.reportSummary?.trim() || "Synthetic report from worker\n[STEP:0]";
  const reportDetailsBase =
    input.reportDetails?.trim() ||
    "No additional details. This is synthetic content generated by operation-debug.";
  const previousResponseBase = input.previousResponse?.trim() || "Synthetic previous movement output";

  const flowSteps: FlowStepPreview[] = [];

  for (let index = 0; index < operation.movements.length; index += 1) {
    const movement = operation.movements[index];
    const previousResponse =
      previousResponseBase || `Synthetic previous movement output for ${movement.name}`;
    const movementState = buildStateForMovement(operation, movement, previousResponse);
    const operationContextSummary = buildOperationContextSummary(operation, movementState);

    if (movement.agent === "noctis") {
      const facets = resolveMovementFacets(operation, movement, language);
      const routedCrystalMessage = buildRoutedMessageEnvelope({
        speaker: "crystal",
        to: "noctis",
        messageType: "chat",
        body: crystalMessageBase,
      });
      const internalContext = buildInjectedPromptContext({
        missionId: "debug-mission",
        sessionId: "debug-noctis-session",
        agent: "noctis",
        allowedWorkers: ["ignis", "gladiolus", "prompto"],
        appRoot: root,
        executionMode: "operation-debug",
      });

      const injectedPrompt = buildActivationInstruction({
        operation,
        movement,
        operationState: movementState,
        facets,
        reportDir: movementState.reportDir,
      });

      flowSteps.push({
        id: `${movement.name}:self`,
        movementName: movement.name,
        movementIndex: index + 1,
        kind: "self",
        hookId: "hook1",
        title: `${movement.name} (Noctis self-movement)`,
        from: "Crystal",
        to: "Noctis",
        summary: "Crystal message enters Hook 1 and context is injected for Noctis.",
        sourceInput: routedCrystalMessage,
        internalContext,
        injectedPrompt,
        effectivePrompt: `${injectedPrompt}\n\n${routedCrystalMessage}`,
        operationContextSummary,
        normalizedMovement: movement,
        resolvedFacets: facets,
        targetAgent: "noctis",
      });
      continue;
    }

    const workerAgent = toWorkerAgent(movement.agent);
    const workerFacets = resolveMovementFacets(operation, movement, language);

    const dispatchInternalContext = buildInjectedPromptContext({
      missionId: "debug-mission",
      sessionId: `debug-${workerAgent}-session`,
      agent: workerAgent,
      appRoot: root,
    });

    const dispatchPrompt = buildAugmentedInstruction({
      movement,
      operation,
      operationState: movementState,
      originalInstruction:
        input.taskInstruction?.trim() ||
        `Synthetic task for ${workerAgent}: implement the current movement as Noctis instructed.`,
      previousResponse: movementState.previousResponse,
      facets: workerFacets,
      reportDir: movementState.reportDir,
    });

    flowSteps.push({
      id: `${movement.name}:dispatch`,
      movementName: movement.name,
      movementIndex: index + 1,
      kind: "dispatch",
      hookId: "hook2",
      title: `${movement.name} (dispatch)` ,
      from: "Noctis",
      to: workerAgent,
      summary: "Task dispatch enters Hook 2 and worker instruction is augmented.",
      sourceInput:
        input.taskInstruction?.trim() ||
        `Synthetic task for ${workerAgent}: implement the current movement as Noctis instructed.`,
      internalContext: dispatchInternalContext,
      injectedPrompt: dispatchPrompt,
      effectivePrompt: dispatchPrompt,
      operationContextSummary,
      normalizedMovement: movement,
      resolvedFacets: workerFacets,
      targetAgent: workerAgent,
    });

    const reportState = buildStateForMovement(operation, movement, previousResponse);
    const reportSummary = `${reportSummaryBase}\n\n[movement:${movement.name}]`;
    const reportDetails = reportDetailsBase;

    const reportResult = processReport({
      operationState: reportState,
      reportBody: reportSummary,
      reportDetails,
      fromAgent: workerAgent,
      taskId: `debug-task-${movement.name}`,
      reportStatus,
    });

    const reportEnvelope = buildTeamMessageEnvelope({
      from: workerAgent,
      to: "noctis",
      type: "report",
      body: reportSummary,
      taskId: `debug-task-${movement.name}`,
      reportStatus,
      details: reportDetails,
    });

    const reportInternalContext = buildInjectedPromptContext({
      missionId: "debug-mission",
      sessionId: "debug-noctis-session",
      agent: "noctis",
      allowedWorkers: ["ignis", "gladiolus", "prompto"],
      appRoot: root,
      executionMode: "operation-debug",
    });

    const transitionText = reportResult.stateTransition
      ? JSON.stringify(reportResult.stateTransition, null, 2)
      : "No transition detected";

    const ruleEvaluation = [
      `report_status: ${reportStatus}`,
      "",
      "--- report summary ---",
      reportSummary,
      "",
      "--- report details ---",
      reportDetails,
      "",
      "--- state transition ---",
      transitionText,
    ].join("\n");

    const effectivePrompt = reportResult.noctisGuidance
      ? `${reportEnvelope}\n\n${reportResult.noctisGuidance}`
      : reportEnvelope;

    flowSteps.push({
      id: `${movement.name}:report`,
      movementName: movement.name,
      movementIndex: index + 1,
      kind: "report",
      hookId: "hook3",
      title: `${movement.name} (report)` ,
      from: workerAgent,
      to: "Noctis",
      summary: "Worker report enters Hook 3, rules are evaluated, guidance is appended.",
      sourceInput: reportEnvelope,
      internalContext: reportInternalContext,
      injectedPrompt: reportResult.noctisGuidance || "(no guidance generated)",
      effectivePrompt,
      ruleEvaluation,
      ruleTransition: transitionText,
      operationContextSummary,
      normalizedMovement: movement,
      resolvedFacets: workerFacets,
      targetAgent: "noctis",
    });
  }

  return {
    flowSteps,
    operation,
    reportDir: "docs/reports",
  };
}
