import { getProjectRoot } from "@/lib/get-project-root.server";
import { readOperationLanguage } from "@/lib/operation-definition/language";
import { resolveStepFacets } from "@/lib/operation-definition/facet-loader";
import { loadOperationByName } from "@/lib/operation-definition/operation-loader";
import type { OperationDefinition, ResolvedFacets, StepDefinition } from "@/lib/operation-definition/types";
import {
  composeTeamMessagePrompt,
  composeUserToNoctisPromptPreview,
  composeWorkerTaskPrompt,
} from "@/lib/prompt-composition-engine";
import {
  buildActivationInstruction,
  buildOperationContextSummary,
} from "@/lib/prompt-composition-engine/operation-prompt-builder";
import type { AgentId, ReportStatus, StepHistoryEntry, WorkerAgentId } from "@/lib/types/mission";
import { createOperationState } from "@/lib/operation-runtime/state";

export type PreviewNodeId = "hook1" | "hook2" | "hook3";
export type FlowStepKind = "self" | "dispatch" | "report";

export interface FlowStepPreview {
  id: string;
  stepName: string;
  stepIndex: number;
  kind: FlowStepKind;
  hookId: PreviewNodeId;
  title: string;
  from: string;
  to: string;
  summary: string;
  sourceInput: string;
  internalContext: string;
  suppressedContext?: string | null;
  injectedPrompt: string;
  effectivePrompt?: string;
  ruleEvaluation?: string;
  ruleTransition?: string;
  operationContextSummary: string;
  normalizedStep: StepDefinition;
  resolvedFacets?: ResolvedFacets;
  targetAgent?: AgentId;
}

export interface OperationDebugBundle {
  flowSteps: FlowStepPreview[];
  operation: OperationDefinition;
  reportDir: string;
}

function toWorkerAgent(agent: string): WorkerAgentId {
  return agent === "ignis" || agent === "gladiolus" || agent === "prompto"
    ? agent
    : "gladiolus";
}

function buildSyntheticHistory(operation: OperationDefinition, currentStepName: string) {
  const now = new Date().toISOString();
  const currentIndex = operation.steps.findIndex((step) => step.name === currentStepName);
  if (currentIndex <= 0) {
    return [] as StepHistoryEntry[];
  }

  return operation.steps.slice(0, currentIndex).map((step, index) => ({
    step: step.name,
    agent: step.agent,
    status: "completed" as const,
    dispatchedAt: now,
    completedAt: now,
    ruleMatched: 0,
    ruleCondition: step.rules[0]?.condition ?? "completed",
    nextStep: operation.steps[index + 1]?.name ?? "COMPLETE",
    summary: `Synthetic summary for ${step.name}`,
  }));
}

function buildStateForStep(
  operation: OperationDefinition,
  step: StepDefinition,
  previousResponse: string,
) {
  const state = createOperationState(operation.name, operation.initial_step);
  const stepIndex = operation.steps.findIndex((item) => item.name === step.name);

  state.currentStep = step.name;
  state.iteration = Math.max(stepIndex, 0);
  state.stepHistory = buildSyntheticHistory(operation, step.name);
  state.previousResponse = previousResponse;
  state.status = "running";

  return state;
}

export function buildOperationDebugBundle(input: {
  userMessage?: string;
  operationName: string;
  previousResponse?: string;
  reportDetails?: string;
  reportRuleIndex?: number;
  reportStatus?: ReportStatus;
  reportSummary?: string;
  taskInstruction?: string;
}): OperationDebugBundle {
  const root = getProjectRoot();
  const operation = loadOperationByName(input.operationName, readOperationLanguage());

  const reportRuleIndex = Number.isInteger(input.reportRuleIndex) ? input.reportRuleIndex : 0;
  const reportStatus = input.reportStatus ?? "completed";
  const userMessageBase =
    input.userMessage?.trim() || "This is a synthetic User message for operation activation.";
  const reportSummaryBase = input.reportSummary?.trim() || "Synthetic report from worker";
  const reportDetailsBase =
    input.reportDetails?.trim() ||
    "No additional details. This is synthetic content generated by operation-debug.";
  const previousStepOutputBase = input.previousResponse?.trim() || "Synthetic previous step output";

  const flowSteps: FlowStepPreview[] = [];

  for (let index = 0; index < operation.steps.length; index += 1) {
    const step = operation.steps[index];
    const previousResponse = previousStepOutputBase || `Synthetic previous step output for ${step.name}`;
    const stepState = buildStateForStep(operation, step, previousResponse);
    const operationContextSummary = buildOperationContextSummary(operation, stepState);

    if (step.agent === "noctis") {
      const facets = resolveStepFacets(operation, step, readOperationLanguage());
      const injectedPrompt = buildActivationInstruction({
        operation,
        step,
        operationState: stepState,
        facets,
        reportDir: stepState.reportDir,
      });
      const composed = composeUserToNoctisPromptPreview({
        context: {
          missionId: "debug-mission",
          sessionId: "debug-noctis-session",
          agent: "noctis",
          allowedWorkers: ["ignis", "gladiolus", "prompto"],
          appRoot: root,
          executionMode: "operation-debug",
        },
        workflowExtension: injectedPrompt,
        userMessage: userMessageBase,
      });

      flowSteps.push({
        id: `${step.name}:self`,
        stepName: step.name,
        stepIndex: index + 1,
        kind: "self",
        hookId: "hook1",
        title: `${step.name} (Noctis self-step)`,
        from: "User",
        to: "Noctis",
        summary: "User message enters Hook 1 and context is injected for Noctis.",
        sourceInput: composed.promptBody,
        internalContext: composed.sharedContext,
        suppressedContext: composed.suppressedContext,
        injectedPrompt,
        effectivePrompt: composed.effectivePrompt,
        operationContextSummary,
        normalizedStep: step,
        resolvedFacets: facets,
        targetAgent: "noctis",
      });
      continue;
    }

    const workerAgent = toWorkerAgent(step.agent);
    const workerFacets = resolveStepFacets(operation, step, readOperationLanguage());
    const dispatchPrompt =
      input.taskInstruction?.trim() ||
      `Synthetic task for ${workerAgent}: implement the current step as Noctis instructed.`;
    const dispatchComposed = composeWorkerTaskPrompt({
      context: {
        missionId: "debug-mission",
        sessionId: `debug-${workerAgent}-session`,
        agent: workerAgent,
        appRoot: root,
      },
      missionId: "debug-mission",
      agentId: workerAgent,
      taskId: `debug-task-${step.name}`,
      originalPrompt: dispatchPrompt,
      operationStateOverride: stepState,
    });

    flowSteps.push({
      id: `${step.name}:dispatch`,
      stepName: step.name,
      stepIndex: index + 1,
      kind: "dispatch",
      hookId: "hook2",
      title: `${step.name} (dispatch)`,
      from: "Noctis",
      to: workerAgent,
      summary: "Task dispatch enters Hook 2 and worker instruction is augmented.",
      sourceInput: dispatchPrompt,
      internalContext: dispatchComposed.sharedContext,
      suppressedContext: dispatchComposed.suppressedContext,
      injectedPrompt: dispatchComposed.workflowExtension || "(no workflow extension generated)",
      effectivePrompt: dispatchComposed.effectivePrompt,
      operationContextSummary,
      normalizedStep: step,
      resolvedFacets: workerFacets,
      targetAgent: workerAgent,
    });

    const reportState = buildStateForStep(operation, step, previousResponse);
    const reportSummary = `${reportSummaryBase}\n\n[step:${step.name}]`;
    const reportDetails = reportDetailsBase;
    const reportComposed = composeTeamMessagePrompt({
      context: {
        missionId: "debug-mission",
        sessionId: "debug-noctis-session",
        agent: "noctis",
        allowedWorkers: ["ignis", "gladiolus", "prompto"],
        appRoot: root,
        executionMode: "operation-debug",
      },
      missionId: "debug-mission",
      from: workerAgent,
      to: "noctis",
      type: "report",
      body: reportSummary,
      taskId: `debug-task-${step.name}`,
      reportStatus,
      ruleIndex: reportRuleIndex,
      details: reportDetails,
      operationStateOverride: reportState,
    });

    const transitionText = reportComposed.stateTransition
      ? JSON.stringify(reportComposed.stateTransition, null, 2)
      : "No transition detected";
    const ruleEvaluation = [
      `report_status: ${reportStatus}`,
      `report_rule_index: ${reportRuleIndex}`,
      "",
      "--- report summary ---",
      reportSummary,
      "",
      "--- report details ---",
      reportDetails,
      "",
      "--- state transition ---",
      transitionText,
    ].join("\n");

    flowSteps.push({
      id: `${step.name}:report`,
      stepName: step.name,
      stepIndex: index + 1,
      kind: "report",
      hookId: "hook3",
      title: `${step.name} (report)`,
      from: workerAgent,
      to: "Noctis",
      summary: "Worker report enters Hook 3, rules are evaluated, guidance is appended.",
      sourceInput: reportComposed.promptBody,
      internalContext: reportComposed.sharedContext,
      suppressedContext: reportComposed.suppressedContext,
      injectedPrompt: reportComposed.workflowExtension || "(no guidance generated)",
      effectivePrompt: reportComposed.effectivePrompt,
      ruleEvaluation,
      ruleTransition: transitionText,
      operationContextSummary,
      normalizedStep: step,
      resolvedFacets: workerFacets,
      targetAgent: "noctis",
    });
  }

  return {
    flowSteps,
    operation,
    reportDir: "docs/reports",
  };
}